const { chromium } = require('playwright');
(async () => {
  const SP = process.argv[2];
  const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
  const p = await b.newPage({ viewport: { width: 1500, height: 900 } });
  const errs = [];
  p.on('pageerror', e => errs.push(e.message));
  await p.goto('file://' + process.cwd() + '/index.html');
  await p.waitForTimeout(500);
  await p.click('#btnExport');
  await p.waitForTimeout(800);
  await p.screenshot({ path: SP + '/ui-export.png' });
  await p.click('#modalClose');
  await p.click('#btnCode');
  await p.waitForTimeout(300);
  const code = await p.$eval('#codeOut', e => e.value);
  await p.fill('#codeIn', code);
  await p.click('#codeDeploy');
  await p.waitForTimeout(300);
  console.log('units after deploy:', await p.evaluate(() => MFApp.S.units.length));
  await p.keyboard.press('KeyR'); await p.keyboard.press('KeyM'); await p.keyboard.press('KeyN');
  await p.click('.thumb >> nth=0');
  await p.click('.thumb >> nth=1', { modifiers: ['Shift'] });
  await p.keyboard.press('KeyG');
  await p.keyboard.down('KeyW'); await p.keyboard.down('KeyA'); await p.waitForTimeout(700); await p.keyboard.up('KeyW'); await p.keyboard.up('KeyA');
  await p.waitForTimeout(300);
  await p.selectOption('#sl-frame', 'tank');
  await p.selectOption('#palPreset', 'Midnight');
  await p.click('#dice-head');
  await p.keyboard.press('Control+KeyZ');
  await p.screenshot({ path: SP + '/ui-after.png' });
  console.log('units:', await p.evaluate(() => MFApp.S.units.length), 'selected:', await p.evaluate(() => MFApp.S.selected.size));
  await p.setViewportSize({ width: 420, height: 900 });
  await p.waitForTimeout(400);
  await p.screenshot({ path: SP + '/ui-mobile.png', fullPage: false });
  if (errs.length) console.log('ERRORS:', errs.join('\n'));
  await b.close();
})();
